name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'  # dispara para qualquer tag no padrão SemVer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print version
        run: echo "Nova versão detectada: $GITHUB_REF"